// Code generated by MockGen. DO NOT EDIT.
// Source: tariffwritehandler.go
//
// Generated by this command:
//
//	mockgen -source=tariffwritehandler.go -destination=testing/tariffwritehandler_mocks.go -package=testing TariffWriter
//

// Package testing is a generated GoMock package.
package testing

import (
	reflect "reflect"
	models "tariff-calculation-service/internal/models"

	gomock "go.uber.org/mock/gomock"
)

// MockTariffWriter is a mock of TariffWriter interface.
type MockTariffWriter struct {
	ctrl     *gomock.Controller
	recorder *MockTariffWriterMockRecorder
}

// MockTariffWriterMockRecorder is the mock recorder for MockTariffWriter.
type MockTariffWriterMockRecorder struct {
	mock *MockTariffWriter
}

// NewMockTariffWriter creates a new mock instance.
func NewMockTariffWriter(ctrl *gomock.Controller) *MockTariffWriter {
	mock := &MockTariffWriter{ctrl: ctrl}
	mock.recorder = &MockTariffWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTariffWriter) EXPECT() *MockTariffWriterMockRecorder {
	return m.recorder
}

// CreateTariff mocks base method.
func (m *MockTariffWriter) CreateTariff(partitionId string, tariff models.Tariff) (*models.Tariff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTariff", partitionId, tariff)
	ret0, _ := ret[0].(*models.Tariff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTariff indicates an expected call of CreateTariff.
func (mr *MockTariffWriterMockRecorder) CreateTariff(partitionId, tariff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTariff", reflect.TypeOf((*MockTariffWriter)(nil).CreateTariff), partitionId, tariff)
}

// DeleteTariff mocks base method.
func (m *MockTariffWriter) DeleteTariff(partitionId, tariffId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTariff", partitionId, tariffId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTariff indicates an expected call of DeleteTariff.
func (mr *MockTariffWriterMockRecorder) DeleteTariff(partitionId, tariffId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTariff", reflect.TypeOf((*MockTariffWriter)(nil).DeleteTariff), partitionId, tariffId)
}

// UpdateTariff mocks base method.
func (m *MockTariffWriter) UpdateTariff(partitionId string, tariff models.Tariff) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTariff", partitionId, tariff)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTariff indicates an expected call of UpdateTariff.
func (mr *MockTariffWriterMockRecorder) UpdateTariff(partitionId, tariff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTariff", reflect.TypeOf((*MockTariffWriter)(nil).UpdateTariff), partitionId, tariff)
}
