// Code generated by MockGen. DO NOT EDIT.
// Source: contracthandler.go
//
// Generated by this command:
//
//	mockgen -source=contracthandler.go -destination=testing/contracthandler_mocks.go -package=testing ContractGetter, Validator
//

// Package testing is a generated GoMock package.
package testing

import (
	reflect "reflect"
	models "tariff-calculation-service/internal/models"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockContractGetter is a mock of ContractGetter interface.
type MockContractGetter struct {
	ctrl     *gomock.Controller
	recorder *MockContractGetterMockRecorder
}

// MockContractGetterMockRecorder is the mock recorder for MockContractGetter.
type MockContractGetterMockRecorder struct {
	mock *MockContractGetter
}

// NewMockContractGetter creates a new mock instance.
func NewMockContractGetter(ctrl *gomock.Controller) *MockContractGetter {
	mock := &MockContractGetter{ctrl: ctrl}
	mock.recorder = &MockContractGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractGetter) EXPECT() *MockContractGetterMockRecorder {
	return m.recorder
}

// GetContract mocks base method.
func (m *MockContractGetter) GetContract(partitionId, contractId string) (*models.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContract", partitionId, contractId)
	ret0, _ := ret[0].(*models.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContract indicates an expected call of GetContract.
func (mr *MockContractGetterMockRecorder) GetContract(partitionId, contractId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContract", reflect.TypeOf((*MockContractGetter)(nil).GetContract), partitionId, contractId)
}

// GetContracts mocks base method.
func (m *MockContractGetter) GetContracts(partitionId string) (*[]models.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContracts", partitionId)
	ret0, _ := ret[0].(*[]models.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContracts indicates an expected call of GetContracts.
func (mr *MockContractGetterMockRecorder) GetContracts(partitionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContracts", reflect.TypeOf((*MockContractGetter)(nil).GetContracts), partitionId)
}

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// ValidateAndSetPathParams mocks base method.
func (m *MockValidator) ValidateAndSetPathParams(ctx *gin.Context, objectPtr any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndSetPathParams", ctx, objectPtr)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateAndSetPathParams indicates an expected call of ValidateAndSetPathParams.
func (mr *MockValidatorMockRecorder) ValidateAndSetPathParams(ctx, objectPtr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndSetPathParams", reflect.TypeOf((*MockValidator)(nil).ValidateAndSetPathParams), ctx, objectPtr)
}
