// Code generated by MockGen. DO NOT EDIT.
// Source: tariffhandler.go
//
// Generated by this command:
//
//	mockgen -source=tariffhandler.go -destination=testing/tariffhandler_mocks.go -package=testing TariffGetter
//

// Package testing is a generated GoMock package.
package testing

import (
	reflect "reflect"
	models "tariff-calculation-service/internal/models"

	gomock "go.uber.org/mock/gomock"
)

// MockTariffGetter is a mock of TariffGetter interface.
type MockTariffGetter struct {
	ctrl     *gomock.Controller
	recorder *MockTariffGetterMockRecorder
}

// MockTariffGetterMockRecorder is the mock recorder for MockTariffGetter.
type MockTariffGetterMockRecorder struct {
	mock *MockTariffGetter
}

// NewMockTariffGetter creates a new mock instance.
func NewMockTariffGetter(ctrl *gomock.Controller) *MockTariffGetter {
	mock := &MockTariffGetter{ctrl: ctrl}
	mock.recorder = &MockTariffGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTariffGetter) EXPECT() *MockTariffGetterMockRecorder {
	return m.recorder
}

// GetTariff mocks base method.
func (m *MockTariffGetter) GetTariff(partitionId, tariffId string) (*models.Tariff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTariff", partitionId, tariffId)
	ret0, _ := ret[0].(*models.Tariff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTariff indicates an expected call of GetTariff.
func (mr *MockTariffGetterMockRecorder) GetTariff(partitionId, tariffId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTariff", reflect.TypeOf((*MockTariffGetter)(nil).GetTariff), partitionId, tariffId)
}

// GetTariffs mocks base method.
func (m *MockTariffGetter) GetTariffs(partitionId string) (*[]models.Tariff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTariffs", partitionId)
	ret0, _ := ret[0].(*[]models.Tariff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTariffs indicates an expected call of GetTariffs.
func (mr *MockTariffGetterMockRecorder) GetTariffs(partitionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTariffs", reflect.TypeOf((*MockTariffGetter)(nil).GetTariffs), partitionId)
}
